tests: allow to run tests in a user defined X server display
This is done through the USEDISPLAY environment variable.
It's useful for running the tests in containerized environments
like chroots.

diff --git a/test/checksc b/test/checksc
--- a/test/checksc
+++ b/test/checksc
@@ -19,6 +19,7 @@
 # along with this program.  If not, see <http://www.gnu.org/licenses/>.
 
 tests_per_group='10'   # number of tests for each group
+display=':0.0'         # the X server display and screen to record from
 scfile='./screencast'  # screencast file to modify and execute
 outdir='test/output'   # output directory for resulting test videos
 live_streaming='true'  # controls if local live streaming tests will be made
@@ -36,11 +37,12 @@ else
     audio_encoder_live='--audio-encoder=mp3lame'
     effects='--fade=both --volume-factor=1.5'
 fi
-[ -n "$AUDIOIN" ] && audio_input="--audio-input=${AUDIOIN}"
+[ -n "$AUDIOIN"    ] && audio_input="--audio-input=${AUDIOIN}"
+[ -n "$USEDISPLAY" ] && display="$USEDISPLAY"
 video_encoder_soft='--video-encoder=theora'
 video_encoder_live='--video-encoder=x264'
 video_encoder_vaapi='--video-encoder=h264_vaapi'
-common_cmd_all="${scfile} --no-notifications --fixed=3.0 --border=0"
+common_cmd_all="${scfile} --no-notifications --fixed=3.0 --display=${display} --border=0"
 common_cmd_soft="${common_cmd_all} ${audio_input} ${audio_encoder} ${video_encoder_soft}"
 common_cmd_live="${common_cmd_all} ${audio_input} ${audio_encoder_live} ${video_encoder_live}"
 common_cmd_vaapi="${common_cmd_all} ${audio_input} ${audio_encoder} ${video_encoder_vaapi} --vaapi-device=${VAAPI}"
@@ -473,6 +475,15 @@ then
     fi
 else
     test_shells="$(sed -n '1p' "$scfile" | sed 's@^#!.*/@@')"
+fi
+
+if [ -n "$USEDISPLAY" ] 
+then
+    if ! xdpyinfo -display "$USEDISPLAY" >/dev/null 2>&1
+    then
+        printf '%s\n' "${color_red}error:${color_off} '${USEDISPLAY}' is not a valid display value on this system, aborting tests" >&2
+        exit 1
+    fi
 fi
 
 # check if webcam tests are enabled
