Changed $message variable to $msg

diff --git a/screencast b/screencast
--- a/screencast
+++ b/screencast
@@ -307,11 +307,11 @@ check_requirements() {
                 }
                 continue
             else
-                message="error:${request_string}'${requirement}' was not found"
-                printf "%s\n" "$message" >&2
+                msg="error:${request_string}'${requirement}' was not found"
+                printf "%s\n" "$msg" >&2
                 printf "%s\n" "       please install ${installname}" >&2
                 [ "$requirement" != "notify-send" ] &&
-                    notify "critical" "5000" "process-stop" "$message"
+                    notify "critical" "5000" "process-stop" "$msg"
                 exit 1
             fi ;
         }
@@ -322,12 +322,12 @@ check_requirements() {
 #                         line arguments, show notification and exit with error
 # arguments: $1 - command line option name (e.g.: "--fade (-e)")
 command_error() {
-    message="error: ${1} option requires an argument"
+    msg="error: ${1} option requires an argument"
     printf "%s\n%s%s\n" \
-           "$message" \
+           "$msg" \
            "       if you need help run 'screencast --help' " \
            "or 'man screencast'" >&2
-    notify "critical" "5000" "process-stop" "$message"
+    notify "critical" "5000" "process-stop" "$msg"
     exit 1
 }
 
@@ -1255,9 +1255,9 @@ case "$format" in
         [ "$video_encoder_setted" = "false" ] && video_encoder="theora"
         ;;
     *)
-        message="'${format}' is not a valid container \
+        msg="'${format}' is not a valid container \
                  format for this program"
-        exit_program "$(printf "%s" "$message" | remove_spaces)"
+        exit_program "$(printf "%s" "$msg" | remove_spaces)"
         ;;
 esac
 
@@ -1292,9 +1292,9 @@ fi
 if [ "$format" = "mp4" ] && [ "$video_encoder" = "vp9" ] 
 then
     # special case for mp4 + vp9 (support is experimental and not enabled)
-    message="support for vp9 encoder in mp4 container format is \
+    msg="support for vp9 encoder in mp4 container format is \
              currently experimental and not enabled"
-    exit_program "$(printf "%s" "$message" | remove_spaces)"
+    exit_program "$(printf "%s" "$msg" | remove_spaces)"
 fi
 if {
        [ "$format" = "mp4" ] && 
